### PR TITLE
Issue 2835

### LINKED ISSUE #2835: ChangeDetectino Bug
it seems to be an issue about change detection.
For example:
- In the Bf carousel component, we want to show or hide arrows depending on the position of the carousel. But you need to click somewhere on the page to trigger the rerendering from angular. Even thou you called changeDetectionRef.markForCheck() in the component. 
- Also if disable buttons when user is scrolling, otherwise the offset will calculate the wrong way

### PR DESCRIPTION
**Pull request by fritzschoff**
close #2835 
would be nice to disable the buttons when it is scrolling for any miss calculation for sliding. but not important right now

### CODE REVIEW

File: libs/ui/src/lib/carousel/carousel.component.ts [hunk 1]
```diff
@@ -9,51 +9,62 @@ import {
...
-      this.showForward = this.onScrolling('right')
-    }
-    this.scroll =  this.scrollable.elementScrolled();
-  } */
+  ngAfterViewInit() {
+    this.showBack$ = this.onScrolling('left');
+    this.showForward$ = this.onScrolling('right');
+
+    this.subBack = this.showForward$.subscribe(value => {
+      this.showForward = value;
```
Comment (fritzschoff) [inline libs/ui/src/lib/carousel/carousel.component.ts:59]: like that change detection is working. No idea why

File: apps/festival/festival/src/app/marketplace/home/home.component.html [hunk 2]
```diff
@@ -23,26 +23,33 @@ <h1>{{ section.title }}</h1>
...
+              <mat-icon svgIcon="arrow_forward"></mat-icon>
+            </a>
+          </div>
+          <bf-slider hideIndicators loop class="dark-contrast-theme">
+            <bf-slide *ngFor="let movie of section.movies$ | async" overlayColor="gradient"
+              [image]="movie.promotionalElements.banner.media">
+              <movie-slide [movie]="movie">
+                <movie-slide-cta>
+                  <ng-container *ngIf="movie.promotionalElements.trailer">
+                    <a mat-flat-button color="accent" [routerLink]="['/c/o/marketplace/title/' + movie.id]"
```
Comment (GrandSchtroumpf) [inline apps/festival/festival/src/app/marketplace/home/home.component.html:40]: use an array format with "," instead of "+" : `[routerLink]="['/c/o/marketplace/title', movie.id]"`

File: libs/ui/src/lib/carousel/carousel.component.ts [hunk 3]
```diff
@@ -64,16 +75,19 @@ export class CarouselComponent /* implements AfterViewInit */ {
...
+  onScrolling(direction: 'right' | 'left') {
     return this.scrollable.elementScrolled().pipe(
       debounceTime(50),
       map(_ => !!this.scrollable.measureScrollOffset(direction)),
       distinctUntilChanged(),
-      tap(_ => this.ngZone.run(() => this.cdr.detectChanges())),
       startWith(direction === 'right'),
-    )
-  } */
+      tap(_ => this.ngZone.run(() => this.cdr.detectChanges())))
```
Comment (GrandSchtroumpf) [inline libs/ui/src/lib/carousel/carousel.component.ts:84]: Remove that if you need to force the change detection after anyway

File: libs/ui/src/lib/carousel/carousel.component.ts (hunk 1 above)
Comment (GrandSchtroumpf) [reply libs/ui/src/lib/carousel/carousel.component.ts:59]: Do something like that then : 
```typescript
this.subForward = this.onScrolling('left').subscribe(showforward => {
  this.showForward = showforward;
  this.zone.run(() => this.cdr.markforCheck()) // or detectChange
})
```
Same for subBack

File: libs/ui/src/lib/carousel/carousel.component.ts [hunk 4]
```diff
@@ -9,51 +9,62 @@ import {
...
+  ngAfterViewInit() {
+    this.showBack$ = this.onScrolling('left');
+    this.showForward$ = this.onScrolling('right');
+
+    this.subBack = this.showForward$.subscribe(value => {
+      this.showForward = value;
+      this.cdr.detectChanges();
+    })
+
+    this.subForward = this.showBack$.subscribe(value => {
```
Comment (GrandSchtroumpf) [inline libs/ui/src/lib/carousel/carousel.component.ts:63]: It's weird to name it `subForward ` for `showBack` I think ^^

File: libs/ui/src/lib/carousel/carousel.component.scss [hunk 5]
```diff
@@ -10,16 +10,18 @@
   scroll-behavior: smooth;
 }
 
-button {
+#button {
```
Comment (GrandSchtroumpf) [inline libs/ui/src/lib/carousel/carousel.component.scss:13]: Id are unique. Use class instead : `class="direction"`

File: libs/ui/src/lib/carousel/carousel.component.scss [hunk 6]
```diff
@@ -10,16 +10,18 @@
...
   position: absolute;
+  background: rgba(255, 255, 255, 0.226);
```
Comment (GrandSchtroumpf) [inline libs/ui/src/lib/carousel/carousel.component.scss:15]: Maybe use mat-mini-fab instead if you want to have a background. and you can have an opacity on hover : 
```typescript
button {
  opacity: 0.5;
}
button:hover {
  opacity: 1;
}
```

Comment (GrandSchtroumpf) [reply libs/ui/src/lib/carousel/carousel.component.scss:15]: If it doesn't work, keep the hardcoded background. But I don't like that so much ^^
