### PR TITLE
Invitation email to event

### LINKED ISSUE #5519: Event invitation is not sent if an org invitation is pending
Classic flow for concierges is:
- inviting a new user to an org
- then inviting that user to the event
This way when the user activates her/his account, the event invitation is here. 

Now this flow doesn't work, the event invitation isn't sent anymore.

### PR DESCRIPTION
**Pull request by Mussuranae**
Fix the invitation email not sent when an user is invited to join org first.
Fix #5519

### CODE REVIEW

File: apps/backend-functions/src/internals/invitations/events.ts [hunk 1]
```diff
@@ -32,14 +32,16 @@ async function onInvitationToAnEventCreate(invitation: InvitationDocument) {
...
   if (!!invitation.toUser) {
     /**
-     * @dev We wants to send this email only if user have an orgId. If not, this means that he already received an
+     * @dev We wants to send this email only if user have an orgId and a validated account. If not, this means that he already received an
      * email inviting him along with his credentials.
     */
     const user = await getDocument<PublicUser>(`users/${invitation.toUser.uid}`);
-    if (!user.orgId) {
+    const hasOrgOrOrgInvitation = await hasUserAnOrgOrIsAlreadyInvited([invitation.toUser.email]);
+    if (!user.orgId && !hasOrgOrOrgInvitation) {
```
Comment (phpgeekfr) [inline apps/backend-functions/src/internals/invitations/events.ts:40]: I think you can use only `hasOrgOrOrgInvitation` because we already check in this method if user have an orgId

**Review by phpgeekfr — APPROVED** [review]

File: apps/backend-functions/src/internals/invitations/events.ts (hunk 1 above)
Comment (Mussuranae) [reply apps/backend-functions/src/internals/invitations/events.ts:40]: Yeah true, I change it
