### PR TITLE
[E2E] : festival - signup test (end)

### LINKED ISSUE #7751: [E2E] Auth Identity Page ( /auth/identity )
- [x] Fill in all fields correctly (pass)
- [x] Fill with an existing company (pass)
- [x] Fill in all fields except one - do this for all available fields (fail)
- [x] Fill in an already used email address (fail)
- [x] Fill in an wrongly formatted email address (fail)
- [x] Fill in different passwords in the password and confirm password field (fail)
- [x] Fill in a password containing less than 6 characters (fail)
- [x] Fill in a password containing more than 24 characters (fail)

### PR DESCRIPTION
**Pull request by n-germain-work**
fix #7751

### CODE REVIEW

File: libs/testing/cypress/node/src/lib/plugins/db.ts [hunk 1]
```diff
@@ -1,17 +1,17 @@
 import { db } from '../testing-cypress';
-import { createUser, createOrganization } from '@blockframes/model';
-import { App, ModuleAccess } from '@blockframes/utils/apps';
+import { createUser, createOrganization, Organization } from '@blockframes/model';
+import { App, ModuleAccess  } from '@blockframes/utils/apps';
```
Comment (phpgeekfr) [inline libs/testing/cypress/node/src/lib/plugins/db.ts:3]: extra space ;)

File: libs/testing/cypress/node/src/lib/plugins/db.ts [hunk 2]
```diff
@@ -48,3 +56,19 @@ export async function acceptUserInOrg(userEmail: string) {
   const { id: invitationId } = invitation.data();
   return db.collection('invitations').doc(invitationId).update({ status: 'accepted' });
 }
+
+export async function getRandomOrgAdmin(orgId: string) {
+  const permissionsRef = await db.doc(`permissions/${orgId}`).get();
+  const permissions = permissionsRef.data();
```
Comment (phpgeekfr) [inline libs/testing/cypress/node/src/lib/plugins/db.ts:62]: use `createPermissions()` to have typed data

File: libs/testing/cypress/node/src/lib/plugins/db.ts [hunk 3]
```diff
@@ -48,3 +56,19 @@ export async function acceptUserInOrg(userEmail: string) {
...
+    return (
+      permissions.roles[userId] === 'superAdmin' ||
+      permissions.roles[userId] === 'admin'
+    );
+  });
+  const randomIndex = Math.floor(Math.random() * adminIds.length);
+  const adminId = adminIds[randomIndex];
+  const adminRef = await db.doc(`users/${adminId}`).get();
+  const admin = adminRef.data();
+  return createUser(admin);
```
Comment (phpgeekfr) [inline libs/testing/cypress/node/src/lib/plugins/db.ts:73]:
```suggestion
  return createUser(adminRef.data());
```

File: libs/testing/cypress/node/src/lib/plugins/db.ts [hunk 4]
```diff
@@ -30,8 +30,16 @@ function getDashboardOrgs(app: App) {
...
-  const ramdomIndex = Math.floor(Math.random() * docs.length);
-  return createOrganization(docs[ramdomIndex].data());
+  // TODO : when issue #8093 is resolved, revert below function code like in PR #7773
+  let organization: Organization;
+  do {
+    const randomIndex = Math.floor(Math.random() * docs.length);
+    console.log(docs.length, randomIndex);
+    const tempOrg = createOrganization(docs[randomIndex].data());
+    const orgHasAdmin = !!(await getRandomOrgAdmin(tempOrg.id)).email;
+    if (orgHasAdmin) organization = tempOrg;
```
Comment (phpgeekfr) [inline libs/testing/cypress/node/src/lib/plugins/db.ts:40]:
```suggestion
    const orgHasAdmin = await getRandomOrgAdmin(tempOrg.id));
    if (orgHasAdmin?.email) organization = tempOrg;
```

**Review by phpgeekfr — APPROVED** [review]
