### PR TITLE
Various fixes around templates and deliveries

### LINKED ISSUE #183: Delete movie materials when delivery is deleted
Delete movie materials if material.deliveriesIds only includes this delivery ID. If DeliveriesIds includes another IDs, just remove the correct delivery ID and don't delete the material.

### LINKED ISSUE #334: Add a timestamp in template when created (same for "save as template" in delivery)

### LINKED ISSUE #337: Set materials stepId to an empty string if the step is deleted in the delivery
If delivery step is deleted, materials with this stepId are pointing to nothing.

### LINKED ISSUE #375: Create a migration process for production deployment
Whenever we'll update the production environment we'll have to make sure users are not using the app in order to run data migrations & functions deploy safely.

We should develop a way to "block" users from using the app when some migration flag is enabled (be mindful of the offline mode / caching content).

### PR DESCRIPTION
**Pull request by ioaNikas**
- [x] Fix #334: add timestamp to template when created.
- [x] Fix #337: set material stepID to an empty string if corresponding step is deleted from delivery.
- [x] Fix #183: corresponding movie materials is deleted when delivery is unsealed and a material is delete.
- [x] Fix #375: created migration process for templates.

### CODE REVIEW

File: apps/backend-functions/src/delete.ts [hunk 1]
```diff
@@ -102,3 +102,36 @@ export const deleteFirestoreDelivery = async (
 
   return true;
 };
+
+export const deleteFirestoreMaterial = async (
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/delete.ts]: My point of view about how to right functions is : 
- When you are using closures (function inside functions) or callbacks use the array function
- When you need to, use the arrow function.
- Else use the normal notation : `async function deleteFirestoreMaterial(...)`

File: apps/backend-functions/src/delete.ts [hunk 2]
```diff
@@ -102,3 +102,36 @@ export const deleteFirestoreDelivery = async (
...
+  const delivery = await getDocument(`deliveries/${context.params.deliveryId}`);
+
+  if (!material) {
+    console.error(`This material doesn't exist !`);
+    return null;
+  }
+
+  const movieMaterial = await getDocument(`movies/${delivery!.movieId}/materials/${material.id}`)
+
+  if (!movieMaterial) {
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/delete.ts]: You should add `if (!movieMaterial || !movieMaterial.deliveriesIds)` so you don't have to force the compiler with "!" later.

File: apps/backend-functions/src/delete.ts [hunk 3]
```diff
@@ -102,3 +102,36 @@ export const deleteFirestoreDelivery = async (
...
+    console.info(`This material doesn't exist on this movie!`);
+    return null;
+  }
+
+  if (movieMaterial!.deliveriesIds.includes(delivery!.id)) {
+    if (movieMaterial!.deliveriesIds.length === 1) {
+      db.doc(`movies/${delivery!.movieId}/materials/${movieMaterial!.id}`).delete()
+    }
+    else {
+      const newdeliveriesIds: string[] = movieMaterial!.deliveriesIds.filter((id: string) => id !== delivery!.id);
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/delete.ts]: You shouldn't have to force the ":string[]" here.

File: apps/backend-functions/src/migrations.ts [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+  org: Organization,
+  template: Template
+) {
+  const newTemplate = { ...template, orgId: org.id, created: serverTimestamp() };
+  delete newTemplate.materialsId;
+  const templateRef = db.doc(`templates/${template.id}`);
+  batch.set(templateRef, newTemplate);
+}
+
+async function migrateOrgsTemplate(batch: WriteBatch, org: Organization): Promise<any> {
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/migrations.ts]: The return type here is actually "Promise<void>"

File: apps/backend-functions/src/utils.ts [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+}
+
+export async function getCollection<T>(path: string): Promise<T[]> {
+  return db
+    .collection(path)
+    .get()
+    .then(collection => collection.docs.map(doc => doc.data() as T));
+}
+
+export async function getDocument(path: string) {
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/utils.ts]: Maybe you want a generic type here

File: apps/backend-functions/src/utils.ts [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+  return db
+    .doc(path)
+    .get()
+    .then(doc => doc.data());
+}
+
+export async function getOrgsOfDelivery(deliveryId: string): Promise<Organization[]> {
+  const stakeholders = await getCollection<Stakeholder>(`deliveries/${deliveryId}/stakeholders`);
+  const promises = stakeholders.map(({ orgId }) => db.doc(`orgs/${orgId}`).get());
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/utils.ts]: Why not using `getDocument` here ? 
```typescript
const promises = stakeholders.map(({orgId}) => getDocument<Organization>(`orgs/${orgId}`))
return Promise.all(promises)
```

File: libs/material/src/lib/delivery/delivery-settings-item/delivery-settings-item.component.ts [hunk 7]
```diff
@@ -11,13 +12,14 @@ export class DeliverySettingsItemComponent {
...
-  constructor(private service: DeliveryService) { }
+  constructor(private service: DeliveryService, private snackbar: MatSnackBar) { }
 
   public edit() {
     this.update.emit();
   }
 
   public removeStep() {
     this.service.removeStep(this.step);
+    this.snackbar.open("'" + this.step.name + "' has been removed.", 'close', { duration: 2000 })
```
Comment (GrandSchtroumpf) [inline libs/material/src/lib/delivery/delivery-settings-item/delivery-settings-item.component.ts]: Use backquotes for better readibility.

File: libs/material/src/lib/template/+state/template.model.ts [hunk 8]
```diff
@@ -1,11 +1,17 @@
 import { Material } from "../../material/+state/material.model";
+import { firestore } from 'firebase/app';
 
-export interface Template {
+
+export interface PartialTemplate {
```
Comment (GrandSchtroumpf) [inline libs/material/src/lib/template/+state/template.model.ts]: You should not call it "PartialTemplate" because `Partial<Template>` exists, and it's not that.
Maybe `BaseTemplate` ?

File: libs/material/src/lib/template/+state/template.model.ts [hunk 9]
```diff
@@ -22,9 +28,10 @@ export interface TemplatesByOrgs {
 /**
  * A factory function that creates Template
  */
-export function createTemplate(template: Partial<Template>) {
-  return template ? {
-    ...template
-  } as Template : {} as Template
+export function createTemplate(template: PartialTemplate): Template {
```
Comment (GrandSchtroumpf) [inline libs/material/src/lib/template/+state/template.model.ts]: You should always verify that you have content: 
```
  return {
    ...(template || {}),
    created: firestore.FieldValue.serverTimestamp()
  }
```

File: libs/material/src/lib/template/template-item/template-item.component.ts [hunk 10]
```diff
@@ -8,9 +8,10 @@ import { MatSnackBar } from '@angular/material';
   styleUrls: ['./template-item.component.scss'],
   changeDetection: ChangeDetectionStrategy.OnPush,
 })
-export class TemplateItemComponent {
+export class TemplateItemComponent{
 
   @Input() template: Template;
+  public creationDate: any;
```
Comment (GrandSchtroumpf) [inline libs/material/src/lib/template/template-item/template-item.component.ts]: Please type it

File: libs/utils/src/lib/firequery/firequery.ts [hunk 11]
```diff
@@ -16,10 +16,10 @@ export class FireQuery extends AngularFirestore {
   async snapshot<T>(path: string): Promise<T> {
     if (path.split('/').length % 2 === 0) {
       const snapshot = await this.collection(path).ref.get();
-      return snapshot.docs.map(doc => doc.data()) as any;
+      return snapshot.docs.map(doc => doc.data()) as any; // TODO: fix typing (doc.data() as T)
```
Comment (GrandSchtroumpf) [inline libs/utils/src/lib/firequery/firequery.ts]: Why you don't do it ?

File: libs/material/src/lib/template/template-item/template-item.component.ts (hunk 10 above)
Comment (ioaNikas) [reply libs/material/src/lib/template/template-item/template-item.component.ts]: Removed it in commit 7894a8747a460f0299d3cb1bfbee6f6ea86af959

File: apps/backend-functions/src/delivery.ts [hunk 12]
```diff
@@ -67,9 +61,10 @@ export async function onDeliveryUpdate (
...
 
   const orgs = await getOrgsOfDelivery(delivery.id);
-  const movie = await getDocument(`movies/${delivery.movieId}`);
+  const movie = await getDocument<Movie>(`movies/${delivery.movieId}`);
   const stakeholderCount = await db
-    .collection(`deliveries/${delivery.id}/stakeholders`).where('isAccepted', '==', true)
+    .collection(`deliveries/${delivery.id}/stakeholders`)
+    .where('isAccepted', '==', true)
     .get()
     .then(snap => snap.size);
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/delivery.ts]: Same here, use Promise.all : 
```javascript
const [orgs, movie, stakeholderCount] = await Promise.all([
  getOrgsOfDelivery(delivery.id),
  getDocument<Movie>(`movies/${delivery.movieId}`),
  db.collection...
]);
```
Maybe you should create a reusable function to get the size too.

File: apps/backend-functions/src/migrations.ts [hunk 13]
```diff
@@ -0,0 +1,94 @@
...
+) {
+  const newTemplate = { ...template, orgId: org.id, created: serverTimestamp() };
+  delete newTemplate.materialsId;
+  const templateRef = db.doc(`templates/${template.id}`);
+  batch.set(templateRef, newTemplate);
+}
+
+async function migrateOrgsTemplate(batch: WriteBatch, org: Organization): Promise<void> {
+  const templates = await getCollection<Template>(`orgs/${org.id}/templates`);
+  const materials = await getCollection<Material>(`orgs/${org.id}/materials`);
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/migrations.ts]: Use promise.all

File: apps/backend-functions/src/migrations.ts [hunk 14]
```diff
@@ -0,0 +1,94 @@
...
+  await Promise.all(promises);
+  return batch.commit();
+}
+
+export async function deleteTemplates() {
+  const batch = db.batch();
+  const orgs = await getCollection<Organization>(`orgs`);
+  const promises = orgs.map(async org => {
+    const nbTemplates = await getCount(`orgs/${org.id}/templates`);
+    const nbMaterials = await getCount(`orgs/${org.id}/materials`);
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/migrations.ts]: promise.all

File: apps/backend-functions/src/stakeholder.ts [hunk 15]
```diff
@@ -117,9 +72,9 @@ export async function onDeliveryStakeholderDelete (
 
   // TODO: Code is very similar to onStakeholderCreate. We should be able to factor some part of it.
 
-  const delivery = await getDocument(`deliveries/${context.params.deliveryID}`);
+  const delivery = await getDocument<Delivery>(`deliveries/${context.params.deliveryID}`);
   const stakeholder = snap.data();
-  const stakeholderOrg = await getDocument(`orgs/${stakeholder!.orgId}`);
+  const stakeholderOrg = await getDocument<Organization>(`orgs/${stakeholder!.orgId}`);
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/stakeholder.ts]: Promise.all

File: apps/backend-functions/src/stakeholder.ts [hunk 16]
```diff
@@ -130,7 +85,7 @@ export async function onDeliveryStakeholderDelete (
     }
 
     try {
-      const movie = await getDocument(`movies/${delivery.movieId}`);
+      const movie = await getDocument<Movie>(`movies/${delivery.movieId}`);
       const orgs = await getOrgsOfDelivery(delivery.id);
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/stakeholder.ts]: Promise.all

File: apps/backend-functions/src/stakeholder.ts [hunk 17]
```diff
@@ -165,9 +120,9 @@ export async function onMovieStakeholderCreate (
 
   // TODO: Code is very similar to onStakeholderCreate. We should be able to factor some part of it.
 
-  const movie = await getDocument(`movies/${context.params.movieID}`);
+  const movie = await getDocument<Movie>(`movies/${context.params.movieID}`);
   const newStakeholder = snap.data();
-  const newStakeholderOrg = await getDocument(`orgs/${newStakeholder!.orgId}`);
+  const newStakeholderOrg = await getDocument<Organization>(`orgs/${newStakeholder!.orgId}`);
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/stakeholder.ts]: You should not use "!" here. Also Promise.all

File: apps/backend-functions/src/stakeholder.ts [hunk 18]
```diff
@@ -223,9 +178,9 @@ export async function onMovieStakeholderDelete (
 
   // TODO: Code is very similar to onStakeholderCreate. We should be able to factor some part of it.
 
-  const movie = await getDocument(`movies/${context.params.movieID}`);
+  const movie = await getDocument<Movie>(`movies/${context.params.movieID}`);
   const stakeholder = snap.data();
-  const stakeholderOrg = await getDocument(`orgs/${stakeholder!.orgId}`);
+  const stakeholderOrg = await getDocument<Organization>(`orgs/${stakeholder!.orgId}`);
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/stakeholder.ts]: Same for ! and Promise.all

File: libs/material/src/lib/template/+state/template.service.ts [hunk 19]
```diff
@@ -81,8 +79,10 @@ export class TemplateService {
       materials.forEach(material => {
         const materialWithoutStep = { ...material, step: null };
         delete materialWithoutStep.step;
-        const materialRef = this.db.doc<Material>(`templates/${template.id}/materials/${material.id}`).ref;
-        return batch.set(materialRef, materialWithoutStep);
+        const materialDoc = this.db.doc<Material>(
```
Comment (GrandSchtroumpf) [inline libs/material/src/lib/template/+state/template.service.ts]: on one line if possible.

File: apps/backend-functions/src/delivery.ts [hunk 20]
```diff
@@ -18,15 +19,29 @@ async function notifyOnNewSignee(delivery: any, orgs: Organization[]): Promise<v
...
+  }
+
+  const [newStakeholderOrg, movie] = await Promise.all([
+    getDocument<Organization>(`orgs/${newStakeholder!.orgId}`),
+    getDocument<Movie>(`movies/${delivery.movieId}`)
+  ]);
+
+  if(!movie) {
+    throw new Error(`This movie doesn't exist !`);
+  } else if (!newStakeholderOrg) {
```
Comment (GrandSchtroumpf) [inline apps/backend-functions/src/delivery.ts]: Don't use `else` here. Just `if (...) { ... } if (...) { ... }`
