### PR TITLE
4.1 Event fixes

### LINKED ISSUE #7980: Release 4.1 - Events
[Screening test scenarios](https://www.notion.so/cascade8/Screening-69f2b3a496394341aa16227d58109eb4)
[Meeting test scenarios](https://www.notion.so/cascade8/Meeting-7d16f2abef1a4b5b85b5a1889dfa1eab)
[Interactions](https://www.notion.so/cascade8/Interactions-244e704f695d45bf9355eebc49e541ce)

Akita for Router has been removed in this release. Which means extra attention needs to be paid whether every link is still working properly and the correct app names are displayed (https://github.com/blockframes/blockframes/issues/7287)

### PR DESCRIPTION
**Pull request by Poppe-A**
#7980

### CODE REVIEW

File: libs/invitation/src/lib/form/user/user.component.ts [hunk 1]
```diff
@@ -116,7 +116,7 @@ export class UserComponent implements OnInit {
         this.sending.next(false);
       } catch (error) {
         this.sending.next(false);
-        this.snackBar.open(error.message, 'close', { duration: 5000 });
+        this.snackBar.open('Something went wrong ...', 'close', { duration: 5000 });
```
Comment (RemcoSimonides) [inline libs/invitation/src/lib/form/user/user.component.ts:119]: I think it's important to know what caused the 'internal' error and fix that instead.

File: libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.ts [hunk 2]
```diff
@@ -20,7 +20,7 @@ export class RequestAskingPriceComponent {
     territories: new FormStaticValueArray<'territories'>([], 'territories', [Validators.required]),
     message: new FormControl()
   });
-
+  public disableSendButton: boolean;
```
Comment (RemcoSimonides) [inline libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.ts:23]: `disableSendButton = false;`

☝️ I also don't specify `public` because it's default by public and I see that the other variable in this class (form) also doesn't specify it. So I'd keep it consistent

**Review by RemcoSimonides — CHANGES_REQUESTED** [review]

File: libs/event/src/lib/guard/event-access.guard.ts [hunk 3]
```diff
@@ -61,8 +61,12 @@ export class EventAccessGuard implements CanActivate {
 
           return true;
         } else {
-          this.snackBar.open('Missing invitation parameter', 'close', { duration: 5000 });
-          await this.authService.deleteAnonymousUser();
+          this.snackBar.open('Sorry, it seems that you were not invited to this event', 'Try with other mail', { duration: 6000 })
```
[the remark this answers is not in the document]
Comment (Poppe-A) [reply libs/event/src/lib/guard/event-access.guard.ts:64]: It was a request from Anastasiia

File: libs/invitation/src/lib/form/user/user.component.ts (hunk 1 above)
Comment (Poppe-A) [reply libs/invitation/src/lib/form/user/user.component.ts:119]: That was also a request from Anastasiia, and I couldn't reproduce the error

**Review by RemcoSimonides — APPROVED** [review]
