### PR TITLE
UI mobile fixes

### LINKED ISSUE #6860: UI Improvements for Mobile
### Archipel Market 

**Google Chrome Version 93.0.4577.63**

**landing page**

- [x] (Global) Have all titles smaller on mobile. 
media-query sm : font-size: 48px / line-height: 1.2;
Antoine: H1 font-size is already 36px. I just changed mat-display-1 and 2

- [x] Off centered buyer logos --> add a line:
"justify-content: center;" on mobile only.
Capture d’écran 2021-09-07 à 13 48 03

- [x] Footer layout broken --> margin bottom; 16px (between logos)
File (6)

**Sign up**

- [x] Increase space between H1 and logo --> margin-top 24px on H1
bfc2f1edee8745d1a07936569a4b6ff3-0001

**Dashboard**

- [x] Wrap button and "+" under H1
File (7)

**Wishlist**

- [x] Add horizontal scroll
File (8)

- [x] Global responsive fix to do on modals. 
media-queries mobile : padding-left and right 24px;
File (11)

Antoine: I think the modals already have a 24px padding. But for some specifics ones we add more padding. So we need to check every modal

**Film detail**

- [x] Can't put the video in fullscreen ? --> Make it bigger on mobile and include option to see it in fullscreen
File (1)

### General Padding

- [x] Replace padding:80px by 20px left and right on mobiles.
Capture d’écran 2021-09-07 à 13 29 44

- [x] same for mat-tab-group
Capture d’écran 2021-09-07 à 13 38 46

### Archipel Market 

**Landing page**

- [x] Center H1
image

**Home**

- [x] This should be written as “We’ve got more”
image

**Film page**

- [x] Center title cards
image

**Sellers**

- [x] Center column
image

### PR DESCRIPTION
**Pull request by Poppe-A**
#6860

### CODE REVIEW

File: libs/movie/src/lib/movie/marketplace/artistic/artistic.component.ts [hunk 1]
```diff
@@ -11,10 +12,12 @@ import { TitleMarketplaceShellComponent } from '../shell/shell.component';
...
 export class ArtisticComponent implements OnInit {
   public movie$ = this.shell.movie$;
-
+  public ltMd$ = this.breakpointsService.ltMd;
+  
   constructor(
     private shell: TitleMarketplaceShellComponent,
-    private dynTitle: DynamicTitleService
+    private dynTitle: DynamicTitleService,
+    private breakpointsService: BreakpointsService,
```
Comment (RemcoSimonides) [inline libs/movie/src/lib/movie/marketplace/artistic/artistic.component.ts:20]: Not used

File: libs/movie/src/lib/movie/marketplace/artistic/artistic.component.scss [hunk 2]
```diff
@@ -1,3 +1,5 @@
+@import "@angular/flex-layout/mq";
```
Comment (RemcoSimonides) [inline libs/movie/src/lib/movie/marketplace/artistic/artistic.component.scss:1]: Not used

File: libs/movie/src/lib/movie/marketplace/artistic/artistic.component.scss [hunk 3]
```diff
@@ -11,4 +13,15 @@ mat-divider {
...
+
+.card-grid {
+  display: grid;
+  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
+  grid-gap: 16px;
+  margin: 24px;
+}
+
+.card-grid-item {
+    grid-column: span 2;
```
Comment (RemcoSimonides) [inline libs/movie/src/lib/movie/marketplace/artistic/artistic.component.scss:26]: Why span it over 2 colums if you can just make the columns double the size?

File: libs/movie/src/lib/movie/marketplace/main/main.component.scss [hunk 4]
```diff
@@ -30,7 +32,16 @@ h5 {
...
-@import '@angular/flex-layout/mq';
+.card-grid {
+  display: grid;
+  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
+  grid-gap: 16px;
+  margin: 24px;
+}
+
+.card-grid-item {
+    grid-column: span 2;
```
Comment (RemcoSimonides) [inline libs/movie/src/lib/movie/marketplace/main/main.component.scss:43]: Same as above

File: libs/movie/src/lib/movie/marketplace/main/main.component.ts [hunk 5]
```diff
@@ -21,11 +22,13 @@ export class MainComponent implements OnInit {
     prizes: ['prizes', 'review'],
   };
   private alreadyPlayed = false;
+  public ltMd$ = this.breakpointsService.ltMd;
 
   constructor(
     private shell: TitleMarketplaceShellComponent,
     private dynTitle: DynamicTitleService,
     private analytics: AnalyticsService,
+    private breakpointsService: BreakpointsService,
```
Comment (RemcoSimonides) [inline libs/movie/src/lib/movie/marketplace/main/main.component.ts:31]: Not used

File: libs/movie/src/lib/movie/marketplace/main/main.component.html [hunk 6]
```diff
@@ -111,12 +111,12 @@ <h2 *ngIf="(movie | hasKeys: keys.prizes) && (movie | hasStatus: status.afterPro
   <!-- Festival -->
   <section *ngIf="(movie.prizes.length || movie.customPrizes.length) && (movie | hasStatus: status.afterProd)">
     <h3>Festivals & Awards</h3>
-    <article grid>
+    <article class="card-grid">
       <ng-container *ngFor="let prize of movie.prizes">
-        <title-prize-card [col]="3" [prize]="prize"></title-prize-card>
+        <title-prize-card class="card-grid-item" [prize]="prize"></title-prize-card>
```
Comment (RemcoSimonides) [inline libs/movie/src/lib/movie/marketplace/main/main.component.html:116]: Remove class if you don't use it anymore

File: libs/movie/src/lib/movie/marketplace/main/main.component.html [hunk 7]
```diff
@@ -111,12 +111,12 @@ <h2 *ngIf="(movie | hasKeys: keys.prizes) && (movie | hasStatus: status.afterPro
...
       </ng-container>
       <ng-container *ngFor="let prize of movie.customPrizes">
-        <title-prize-card [col]="3" [prize]="prize"></title-prize-card>
+        <title-prize-card class="card-grid-item" [prize]="prize"></title-prize-card>
```
Comment (RemcoSimonides) [inline libs/movie/src/lib/movie/marketplace/main/main.component.html:119]: Remove class if you don't use it anymore

File: libs/movie/src/lib/movie/marketplace/artistic/artistic.component.html [hunk 8]
```diff
@@ -3,21 +3,20 @@ <h2 *ngIf="movie | hasKeys: ['cast', 'crew']">Artistic Information</h2>
...
   </section>
 
-
   <section *ngIf="movie.crew.length">
     <h3>Crew Members</h3>
-    <article grid>
+    <article class="card-grid">
       <ng-container *ngFor="let crew of movie.crew">
-        <title-credit-card [col]="3" [credit]="crew" type="crew"></title-credit-card>
+        <title-credit-card class="card-grid-item" [credit]="crew" type="crew"></title-credit-card>
```
Comment (RemcoSimonides) [inline libs/movie/src/lib/movie/marketplace/artistic/artistic.component.html:19]: Remove class if you don't use it anymore

File: libs/movie/src/lib/movie/marketplace/artistic/artistic.component.html [hunk 9]
```diff
@@ -3,21 +3,20 @@ <h2 *ngIf="movie | hasKeys: ['cast', 'crew']">Artistic Information</h2>
 
   <section *ngIf="movie.cast.length">
     <h3>Cast Members</h3>
-    <article grid>
+    <article class="card-grid">
       <ng-container *ngFor="let cast of movie.cast">
-        <title-credit-card [col]="3" [credit]="cast" type="cast"></title-credit-card>
+        <title-credit-card class="card-grid-item" [credit]="cast" type="cast"></title-credit-card>
```
Comment (RemcoSimonides) [inline libs/movie/src/lib/movie/marketplace/artistic/artistic.component.html:8]: Remove class if you don't use it anymore

File: libs/movie/src/lib/movie/marketplace/main/main.component.html [hunk 10]
```diff
@@ -95,9 +95,9 @@ <h5>Running time</h5>
   <!-- Directors -->
   <section *ngIf="movie.directors.length">
     <h3>Directors</h3>
-    <article grid>
+    <article class="card-grid">
       <ng-container *ngFor="let director of movie.directors">
-        <title-credit-card [col]="3" [credit]="director" type="director"></title-credit-card>
+        <title-credit-card class="card-grid-item" [credit]="director" type="director"></title-credit-card>
```
Comment (RemcoSimonides) [inline libs/movie/src/lib/movie/marketplace/main/main.component.html:100]: Remove class if you don't use it anymore

File: libs/user/src/lib/auth/components/signin-form/signin-form.component.html [hunk 11]
```diff
@@ -29,7 +29,7 @@ <h1>Log in</h1>
       <a type="button" mat-button routerLink="../reset-password" class="forgot-password">Forgot your password?</a>
       <div fxLayout="column" fxLayoutAlign="center center">
         <button class="submit" type="submit" mat-flat-button color="accent" test-id="submit"><ng-content select="[buttonText]"></ng-content></button>
-        <a id="tosignup" type="button" color="accent" mat-button routerLink="/auth/identity">Not having an account? Sign up here.</a>
+        <a id="tosignup" type="button" color="accent" mat-button routerLink="/auth/identity">Not having an account? <br fxHide.gt-xs> Sign up here.</a>
```
Comment (RemcoSimonides) [inline libs/user/src/lib/auth/components/signin-form/signin-form.component.html:32]: use `display: none;` instead of fxHide.
I think this is not designed well btw. It should either wrap normally, or have two separate sentences with different UI.

**Review by RemcoSimonides — APPROVED** [review]
