### PR TITLE
Release event fixes

### LINKED ISSUE #7764: Release 4.0 - Events
[Screening test scenarios](https://www.notion.so/cascade8/Screening-69f2b3a496394341aa16227d58109eb4)
[Meeting test scenarios](https://www.notion.so/cascade8/Meeting-7d16f2abef1a4b5b85b5a1889dfa1eab)
[Interactions](https://www.notion.so/cascade8/Interactions-244e704f695d45bf9355eebc49e541ce)

Issues fixed during this release

Event page
- [ ] https://github.com/blockframes/blockframes/issues/7570

Events calendar:
- [ ] https://github.com/blockframes/blockframes/issues/6603

Meeting
- [ ] Twilio Akita has been removed (https://github.com/blockframes/blockframes/issues/7274)

Akita has been removed for Invitations, Notifications, Meeting (Twilio), Contract, Bucket, Offer, Income, Campaign, Organisation, Permissions, User & Auth. This means that anything can be broken. For example some parts of the page don't load or missing information on pages. Let's find what has been broken if anything! :)

### PR DESCRIPTION
**Pull request by Poppe-A**
#7764

### CODE REVIEW

File: libs/event/src/lib/components/request-screening/request-screening.component.ts [hunk 1]
```diff
@@ -36,6 +36,7 @@ export class RequestScreeningComponent {
 
   async requestScreening() {
     this.animated = false;
+    this.snackbar.open('Sending your screening request...', '', { duration: 3000 });
```
Comment (phpgeekfr) [inline libs/event/src/lib/components/request-screening/request-screening.component.ts:39]: I think the snackbar should stay until the next one ( `this.snackbar.open('Screening request successfully sent', '', { duration: 3000 });` ) is displayed.


```
const snackbarRef = this.snackbar.open('Sending your screening request...');

```
and when needed:

```
snackbarRef.dismiss();
```

Like for Export PDF as asked in the issue `apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts`
