### PR TITLE
Design Review

### LINKED ISSUE #2910: DESIGN REVIEW - Toolbar
- [x] calendar and heart icons should be in grey, like invitation and bell icons
image
wrong
image
right
- [x] calendar icon isn't center
- [x] 24px between name and profil picture
- [x] 32px between bell picture and name
- [x] padding right and left 24px inside the toolbar

### LINKED ISSUE #2911: DESIGN REVIEW - Header banner / Marketplace home page
Header banner :
image
- [x] padding top and bottom inside the banner 100px
- [x] padding right and left inside the banner 96px
- [x] Use typo display-2 to "The endless film market"
- [x] No margin between "WELCOME TO ARCHIPEL MARKET" and "The endless film market"
- [x] margin 80px between "The endless film market" and flat button

image
- [x] Forgot and other stroked button
- [x] margin 80px before the first carrousel

### LINKED ISSUE #2916: DESIGN REVIEW - Slider / Marketplace home page
I don't recommend using it right in the middle of the page. This is done to take the entire screen as a header. Here it doesn't make sense to be used like that.

image
- [x] H4 all the time in capital letters, no margin bottom
image
- [x] H2 margin bottom 8px
image
- [x] Flat Button primary
image
- [x] 40px between body-1 and flat button
image
- [x] 32px between button and body-2
image
- [x] use body-2
- [x] stop text before the end
image
- [x] isn't the right component. Need to use Icon button + caption texte, not basic button + left icon
image
- [ ] Use fab button
image
- [x] 80px between the end and carrousel
image

### PR DESCRIPTION
**Pull request by Mussuranae**
Toolbar design review
Fix #2910 
Header on home page marketplace
Fix #2911 
Slider for marketplace home page
Fix #2916 

Add also placeholder for movie card depending on the size given to the movie-card

### CODE REVIEW

File: libs/movie/src/lib/movie/components/card/card.component.ts [hunk 1]
```diff
@@ -9,11 +9,20 @@ import { scaleIn } from '@blockframes/utils/animations/fade';
...
   @Input() movie: Movie;
   @Input() link = "..";
+
+  ngOnInit() {
+    if (this.size === 'banner') {
+      this.placeholder = 'empty_slider.webp';
+    } else {
+      this.placeholder = 'empty_poster.webp';
+    }
+  }
```
Comment (Hugo-Hontans) [inline libs/movie/src/lib/movie/components/card/card.component.ts:26]: You can do a getter instead of ngOnInit
