### PR TITLE
7703 fix identity form no org

### LINKED ISSUE #7703: An user that have no org cannot fill the identity form
If I try to login with an user that have no orgId (and no invitation) but  lastName and FirstName already set, I'm redirected to `/auth/identity`

But when every field is filled the "Sign in" button stays disabled :

with, a not accurate message : `Please enter valid name and surname`

```
    if (this.form.invalid) {
      this.snackBar.open('Please enter valid name and surname', 'close', { duration: 2000 });
      return;
    }
```

 I think this is due to the fact that some inputs are disabled ( for example lastName is already filled and I'm not supposed to edit this)

This issue can occur on production but I don't really know in which condition an user can be without any org and any invitations unless user was removed from org or if invitation/request to join org was refused.

user example on staging : `078k6zjt65aBL3Wz6u9v23LJuFK2` `dev+anissa-dxj@blockframes.io`

So to reproduce, we must use an user with lastName and firstName but without any organization or invitation to joinOrg and I have the feeling that this can only happen on staging, because during anonymization process, even  user without any last org firstName will be filled with a random one or on production if  user was removed from org or if invitation/request to join org was refused.

This does not look like an urgent issue but we should try to remove an user from org and check if he can ask to join an existing or create a new one.
And maybe fix this error for the next release

### PR DESCRIPTION
**Pull request by RemcoSimonides**
Fix #7703
https://github.com/blockframes/blockframes/issues/7756#issuecomment-1041814085

### CODE REVIEW

File: libs/user/src/lib/auth/pages/identity/identity.component.ts [hunk 1]
```diff
@@ -109,7 +109,8 @@ export class IdentityComponent implements OnInit, OnDestroy {
     return this.intercom.show();
   }
 
-  private updateFormForExistingIdentity(user: Partial<PublicUser>) {
+  private updateFormForExistingIdentity(profile: Partial<User>) {
+    const user = createPublicUser(profile);
```
Comment (RemcoSimonides) [inline libs/user/src/lib/auth/pages/identity/identity.component.ts:113]: Removes `privacyPolicy: { ip: '', ... }` from the object.
This ticked the privacy policy box already on the form. It shouldn't be ticked already, but that has to do with this issue open https://github.com/blockframes/blockframes/issues/6908

File: libs/utils/src/lib/form/validators/validators.ts [hunk 2]
```diff
@@ -43,7 +43,7 @@ export function confirmPasswords(
 /** Require current and new password to be different */
 export function differentPassword(current: string = 'current', next: string = 'next'): ValidatorFn {
   return (group: FormGroup): { [key: string]: boolean } | null => {
-    return group.controls[current].value === group.controls[next].value
+    return group.controls[current].value === group.controls[next].value && !group.controls[current].disabled && !group.controls[next].disabled
```
Comment (GrandSchtroumpf) [inline libs/utils/src/lib/form/validators/validators.ts:46]: it's not readable, please create intermediary variables : 
```suggestion
    const currentControl = group.controls[current];
    const nextControl = group.controls[next];
    if (currentControl !== nextControl.value) return null;
    if (currentControl.disabled && nextControl.disabled) return null;
    return { currentPasswordMatch: true };
```

**Review by GrandSchtroumpf — APPROVED** [review]
