### PR TITLE
Multiple sanity fixes

### LINKED ISSUE #3897: Cannot crop again the same file when uploading image
If I first upload my-image.png  and then I want to upload it again to crop it differently, since the two images have the same fileName, there will be a conflict

### LINKED ISSUE #3926: Better functions error handling in players
Players components call the backend-function `privateVideo`. This function can fail for various reasons. The components just check for errors and simply throw if any error happen.

We could have a more user friendly error handleing.

### LINKED ISSUE #3939: Dashboard Movie view - Button to see film on marketplace
We should add a button for the sales agents to go directly from their movie page on dashboard to their movie page on marketplace. 
Before creating the UI would be good to have a UX proposition on where to place that button

### LINKED ISSUE #4299: JW Player dev env
Would be good to have a side env for devs to make your tests outside the prod videos

### PR DESCRIPTION
**Pull request by pldespaigne**
- [x] fix #3939 
- [x] fix #3897 
- [x] fix #3926 
- [x] fix #4299

### CODE REVIEW

File: libs/media/src/lib/components/cropper/cropper.component.ts [hunk 1]
```diff
@@ -196,8 +199,10 @@ export class CropperComponent implements OnInit {
 
       this.nextStep('show');
 
-      // regexp selects part of string after the last . in the string (which is always the file extension) and replaces this by '.webp'
-      const fileName = sanitizeFileName(this.file.name.replace(/(\.[\w\d_-]+)$/i, '.webp'));
+      // regexp selects part of string after the last . in the string (which is always the file extension)
```
Comment (fritzschoff) [inline libs/media/src/lib/components/cropper/cropper.component.ts:202]: you mean regex?

**Review by fritzschoff — APPROVED** [review]

File: libs/media/src/lib/components/cropper/cropper.component.ts (hunk 1 above)
Comment (pldespaigne) [reply libs/media/src/lib/components/cropper/cropper.component.ts:202]: didn't write it but yup ^^
