### PR TITLE
8702 fix loading pie chart

### LINKED ISSUE #8702: Sellers' analytics - Buyers' Activities - Pie chart loading super long
app: festival
page: c/o/dashboard/home/buyer

I went on seller with a good amount of analytics and the pie chart is super long to load (2-3min) though the numbers itself are loaded.

### PR DESCRIPTION
**Pull request by RemcoSimonides**
fix #8702
To reproduce the bug consistently I went to
1. /c/o/dashboard/title
2. Navigate to Dashboard
3. Click on "View all Buyers' Activitites"

On /c/o/dashboard/title, all the titles of the sellers org are queried. When going to the Buyers Activities page, it triggers the observables twice. First is for the sellers' org, and then again with more data. This is a bug that has been seen on CRM before.

However, this time, the `orgService.valueChanges(orgIds)` kept triggering infinitely (and thus the pie chart kept trying to re-render). Turning of memorization helped, or changing valueChangess to getValue also helped.

This is likely a bug in ngfire lib 

Might be caused by the same bug as https://github.com/blockframes/blockframes/issues/8509

### CODE REVIEW

File: libs/organization/src/lib/organization/service.ts [hunk 1]
```diff
@@ -27,6 +27,7 @@ import { BlockframesCollection } from '@blockframes/utils/abstract-service';
 @Injectable({ providedIn: 'root' })
 export class OrganizationService extends BlockframesCollection<Organization> {
   readonly path = 'orgs';
+  readonly memorize = false;
```
Comment (RemcoSimonides) [inline libs/organization/src/lib/organization/service.ts:30]: Another solution would have been to use `getValue()` instead of `valueChanges()` in the query.

Comment (GrandSchtroumpf) [reply libs/organization/src/lib/organization/service.ts:30]: If you don't care about realtime update you can use `load()`, it's an alias to `firstValueFrom(valueChanges())`

**Comment by GrandSchtroumpf** [comment]
So it's only the orgService which is infinitely triggering ? Not the MovieService nor the UserService ?
Is the current orgId part of the `orgIds` here: `orgs: ({ orgIds }) => this.orgService.valueChanges(orgIds)` ?

**Review by GrandSchtroumpf — APPROVED** [review]
