### PR TITLE
fix Public org page line-up not complete

### LINKED ISSUE #4762: Public org page line-up not complete
URL: https://staging.archipelmarket.com/c/o/marketplace/organization/sLchj1Ib4Cxhwr0ZBW4m/title
https://staging.archipelmarket.com/c/o/dashboard/title
User: dev+camilla-swf@blockframes.io

Line-up shows 2 films while I got more than 20 accepted films on dashboard

This list is supposed to display: all movies that belong to the org that are accepted and linked to that application

### PR DESCRIPTION
**Pull request by phpgeekfr**
fix #4762

### CODE REVIEW

File: libs/firebase-utils/src/lib/firestoreMigrations/0049.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+  const movies = await db.collection('movies').get();
+
+  await runChunks(movies.docs, async (movie) => {
+    const data = movie.data() as MovieDocument;
+
+    if (!data._meta.createdAt) {
+      if(data.orgIds.length) {
+        const org = await getDocument<OrganizationDocument>(`orgs/${data.orgIds[0]}`);
+        data._meta.createdAt = org._meta.createdAt;
+        await movie.ref.set(data);
```
Comment (RemcoSimonides) [inline libs/firebase-utils/src/lib/firestoreMigrations/0049.ts:16]: Maybe combine the promises

**Review by RemcoSimonides — APPROVED** [review]
LGTM
