### PR TITLE
Fix cypress not found in backend issue

### LINKED ISSUE #6561: cannot use "('Cypress' in window)" in backend functions
In 
```
export async function userFirstConnexion(user: PublicUser): Promise<EmailRequest> {
  const supportEmail = ('Cypress' in window) ? testEmail : getSupportEmail(user._meta.createdFrom);
  return {
    to: supportEmail,
    subject: 'New user connexion',
    text: userFirstConnexionTemplate(user)
  };
}
```

Related sentry error : https://sentry.io/organizations/cascade-8/issues/2615348959/?environment=staging&project=1540126&query=is%3Aunresolved

Looks like it is preventing email to be sent.

@xmano already fixed this but on a branch that is not yet on release/3.4

### PR DESCRIPTION
**Pull request by xmano**
Fixes #6561

### CODE REVIEW

File: apps/backend-functions/src/environments/environment.ts [hunk 1]
```diff
@@ -5,6 +5,7 @@
  * Use this setup (non-production) when the execution context is outside firebase
  * functions.
  */
+export const e2e_mode = true;
```
Comment (phpgeekfr) [inline apps/backend-functions/src/environments/environment.ts:8]: is it supposed to be true here ?

Comment (xmano) [reply apps/backend-functions/src/environments/environment.ts]: Ok making default `false` and added a comment to clarify.

**Review by phpgeekfr — APPROVED** [review]
